In [28]:
import numpy as np
from scipy import linalg

import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

# Matrix exponantiation

[**Matrix exponential**](https://en.wikipedia.org/wiki/Matrix_exponential) is defined as:

$$\Large e^M = \sum_{k=0}^{\infty} \frac{1}{k!}M^k$$

and can be used to solve systems of linear differential equations. 

## Data

In [42]:
A = np.array([
    [0, -np.pi],
    [np.pi, 0]
])

In [43]:
A 

array([[ 0.        , -3.14159265],
       [ 3.14159265,  0.        ]])

## $exp(M)$

In [44]:
def matrix_exp(matrix, t):
    if t == 0:
        return np.eye(matrix.shape[0])
    else:
        return matrix_exp(matrix, t - 1) + (1 / np.math.factorial(t)) * np.linalg.matrix_power(matrix, t)

In [52]:
matrix_exp(A, 100)

array([[-1.00000000e+00, -3.58877235e-16],
       [ 3.58877235e-16, -1.00000000e+00]])

In [54]:
# Sanity check
linalg.expm(A)

array([[-1.00000000e+00, -2.35127499e-16],
       [ 2.35127499e-16, -1.00000000e+00]])